import type { PlantData } from "@algarden/shared";

export const mockPlant: PlantData = {
  id: "plantId-0",
  growthStage: "SPROUT",
  nodeCount: 1,
  seedId: "seedId-0",
  gardenId: "gardenId-0",
  plantNodes: [
    {
      // root node
      id: "nodeId-0",
      hue: 120,
      size: 50,
      depth: 0,
      angle: null,
      length: null,
      mutationType: null,
      mutationProgress: 0,
      mutationBlueprint: null,
      canSpawn: true,
      parentId: null,
      todoId: null,
      plantId: "plantId-0",
      createdAt: "",
    },
    {
      // root child node 1
      id: "nodeId-1",
      hue: 100,
      size: 30,
      depth: 1,
      angle: 90,
      length: 50,
      mutationType: null,
      mutationProgress: 0,
      mutationBlueprint: null,
      canSpawn: true,
      parentId: "nodeId-0",
      todoId: null,
      plantId: "plantId-0",
      createdAt: "",
    },
    {
      // root child node 2
      id: "nodeId-2",
      hue: 80,
      size: 50,
      depth: 1,
      angle: 135,
      length: 80,
      mutationType: null,
      mutationProgress: 0,
      mutationBlueprint: null,
      canSpawn: true,
      parentId: "nodeId-0",
      todoId: null,
      plantId: "plantId-0",
      createdAt: "",
    },
  ],
  plantEdges: [],
};
